name: Honeytrap
title: Honeytrap
url: http://docs.honeytrap.io/
description: Honeypot framework
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
# disabled gems
#  - jekyll-redirect-from

include: [_redirects,_headers]

# SEO
logo: /images/favicon.png
twitter:
  username: honeytrap

# empty array for tabs
emptyArray: []

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - config
  - search


